### ISSUE TITLE
npm package setup required

### ISSUE THREAD

**Issue by timimsms** [timimsms/cu#5]
## npm Package Setup Checklist

This issue tracks the manual steps required to enable npm distribution after PR #4 is merged.

### Prerequisites
- [ ] Create npm account at https://www.npmjs.com if you don't have one
- [ ] Verify email address on npm

### Package Setup
- [ ] Reserve package name by publishing initial version:
  ```bash
  cd npm
  npm login
  npm publish --access public
  ```
- [ ] Verify package at https://www.npmjs.com/package/@clickup/cli

### GitHub Configuration
- [ ] Generate npm token:
  1. Go to https://www.npmjs.com/settings/[username]/tokens
  2. Create new token with "Automation" type
  3. Copy the token
- [ ] Add `NPM_TOKEN` to GitHub secrets:
  1. Go to Settings → Secrets and variables → Actions
  2. Add new secret named `NPM_TOKEN`
  3. Paste the npm token value

### Release Workflow Update
- [ ] Add npm publish step to `.github/workflows/release.yml`:
  ```yaml
  - name: Publish to npm
    if: success()
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_REF_NAME: ${{ github.ref_name }}
    run: |
      ./scripts/publish-npm.sh
  ```

### Verification
- [ ] Create a test release to verify npm publishing works
- [ ] Test installation: `npm install -g @clickup/cli`
- [ ] Verify binary downloads and runs correctly

## Important Notes

- The package name `@clickup/cli` requires either:
  - Ownership of the `@clickup` npm organization
  - Or use an alternative like `clickup-cli` (without scope)
- First version must be published manually to claim the name
- npm tokens expire after 1 year by default

## Alternative Package Names

If `@clickup/cli` is not available, consider:
- `clickup-cli`
- `cu-cli`
- `@timimsms/clickup-cli` (personal scope)

---
Related to PR #4
